// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: proto/service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollModelRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OwnerId            string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Conv1Weights       [][]byte               `protobuf:"bytes,2,rep,name=conv1_weights,json=conv1Weights,proto3" json:"conv1_weights,omitempty"`
	Conv1Bias          []byte                 `protobuf:"bytes,3,opt,name=conv1_bias,json=conv1Bias,proto3" json:"conv1_bias,omitempty"`
	Conv2Weights       [][]byte               `protobuf:"bytes,4,rep,name=conv2_weights,json=conv2Weights,proto3" json:"conv2_weights,omitempty"`
	Conv2Bias          []byte                 `protobuf:"bytes,5,opt,name=conv2_bias,json=conv2Bias,proto3" json:"conv2_bias,omitempty"`
	Fc1Weights         [][]byte               `protobuf:"bytes,6,rep,name=fc1_weights,json=fc1Weights,proto3" json:"fc1_weights,omitempty"`
	Fc1Bias            []byte                 `protobuf:"bytes,7,opt,name=fc1_bias,json=fc1Bias,proto3" json:"fc1_bias,omitempty"`
	Fc2Weights         []byte                 `protobuf:"bytes,8,opt,name=fc2_weights,json=fc2Weights,proto3" json:"fc2_weights,omitempty"`
	Fc2Bias            []byte                 `protobuf:"bytes,9,opt,name=fc2_bias,json=fc2Bias,proto3" json:"fc2_bias,omitempty"`
	PublicKey          []byte                 `protobuf:"bytes,10,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	RelinearizationKey []byte                 `protobuf:"bytes,11,opt,name=relinearization_key,json=relinearizationKey,proto3" json:"relinearization_key,omitempty"`
	RotationKeys       [][]byte               `protobuf:"bytes,12,rep,name=rotation_keys,json=rotationKeys,proto3" json:"rotation_keys,omitempty"`
	RequestStartTime   int64                  `protobuf:"varint,13,opt,name=request_start_time,json=requestStartTime,proto3" json:"request_start_time,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EnrollModelRequest) Reset() {
	*x = EnrollModelRequest{}
	mi := &file_proto_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollModelRequest) ProtoMessage() {}

func (x *EnrollModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollModelRequest.ProtoReflect.Descriptor instead.
func (*EnrollModelRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollModelRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *EnrollModelRequest) GetConv1Weights() [][]byte {
	if x != nil {
		return x.Conv1Weights
	}
	return nil
}

func (x *EnrollModelRequest) GetConv1Bias() []byte {
	if x != nil {
		return x.Conv1Bias
	}
	return nil
}

func (x *EnrollModelRequest) GetConv2Weights() [][]byte {
	if x != nil {
		return x.Conv2Weights
	}
	return nil
}

func (x *EnrollModelRequest) GetConv2Bias() []byte {
	if x != nil {
		return x.Conv2Bias
	}
	return nil
}

func (x *EnrollModelRequest) GetFc1Weights() [][]byte {
	if x != nil {
		return x.Fc1Weights
	}
	return nil
}

func (x *EnrollModelRequest) GetFc1Bias() []byte {
	if x != nil {
		return x.Fc1Bias
	}
	return nil
}

func (x *EnrollModelRequest) GetFc2Weights() []byte {
	if x != nil {
		return x.Fc2Weights
	}
	return nil
}

func (x *EnrollModelRequest) GetFc2Bias() []byte {
	if x != nil {
		return x.Fc2Bias
	}
	return nil
}

func (x *EnrollModelRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *EnrollModelRequest) GetRelinearizationKey() []byte {
	if x != nil {
		return x.RelinearizationKey
	}
	return nil
}

func (x *EnrollModelRequest) GetRotationKeys() [][]byte {
	if x != nil {
		return x.RotationKeys
	}
	return nil
}

func (x *EnrollModelRequest) GetRequestStartTime() int64 {
	if x != nil {
		return x.RequestStartTime
	}
	return 0
}

type EnrollModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollModelResponse) Reset() {
	*x = EnrollModelResponse{}
	mi := &file_proto_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollModelResponse) ProtoMessage() {}

func (x *EnrollModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollModelResponse.ProtoReflect.Descriptor instead.
func (*EnrollModelResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollModelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnrollModelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InferenceRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ClientId           string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	EncryptedInput     [][]byte               `protobuf:"bytes,2,rep,name=encrypted_input,json=encryptedInput,proto3" json:"encrypted_input,omitempty"`
	PublicKey          []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	RelinearizationKey []byte                 `protobuf:"bytes,4,opt,name=relinearization_key,json=relinearizationKey,proto3" json:"relinearization_key,omitempty"`
	RotationKeys       [][]byte               `protobuf:"bytes,5,rep,name=rotation_keys,json=rotationKeys,proto3" json:"rotation_keys,omitempty"`
	RequestStartTime   int64                  `protobuf:"varint,6,opt,name=request_start_time,json=requestStartTime,proto3" json:"request_start_time,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InferenceRequest) Reset() {
	*x = InferenceRequest{}
	mi := &file_proto_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceRequest) ProtoMessage() {}

func (x *InferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceRequest.ProtoReflect.Descriptor instead.
func (*InferenceRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *InferenceRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *InferenceRequest) GetEncryptedInput() [][]byte {
	if x != nil {
		return x.EncryptedInput
	}
	return nil
}

func (x *InferenceRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *InferenceRequest) GetRelinearizationKey() []byte {
	if x != nil {
		return x.RelinearizationKey
	}
	return nil
}

func (x *InferenceRequest) GetRotationKeys() [][]byte {
	if x != nil {
		return x.RotationKeys
	}
	return nil
}

func (x *InferenceRequest) GetRequestStartTime() int64 {
	if x != nil {
		return x.RequestStartTime
	}
	return 0
}

type InferenceResponse struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	EncryptedResult             []byte                 `protobuf:"bytes,1,opt,name=encrypted_result,json=encryptedResult,proto3" json:"encrypted_result,omitempty"`
	DecryptionProtocolStartTime int64                  `protobuf:"varint,2,opt,name=decryption_protocol_start_time,json=decryptionProtocolStartTime,proto3" json:"decryption_protocol_start_time,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *InferenceResponse) Reset() {
	*x = InferenceResponse{}
	mi := &file_proto_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceResponse) ProtoMessage() {}

func (x *InferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceResponse.ProtoReflect.Descriptor instead.
func (*InferenceResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{3}
}

func (x *InferenceResponse) GetEncryptedResult() []byte {
	if x != nil {
		return x.EncryptedResult
	}
	return nil
}

func (x *InferenceResponse) GetDecryptionProtocolStartTime() int64 {
	if x != nil {
		return x.DecryptionProtocolStartTime
	}
	return 0
}

type PartialDecryptionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EncryptedResult  []byte                 `protobuf:"bytes,1,opt,name=encrypted_result,json=encryptedResult,proto3" json:"encrypted_result,omitempty"`
	PartyId          string                 `protobuf:"bytes,2,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	RequestStartTime int64                  `protobuf:"varint,3,opt,name=request_start_time,json=requestStartTime,proto3" json:"request_start_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PartialDecryptionRequest) Reset() {
	*x = PartialDecryptionRequest{}
	mi := &file_proto_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartialDecryptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialDecryptionRequest) ProtoMessage() {}

func (x *PartialDecryptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialDecryptionRequest.ProtoReflect.Descriptor instead.
func (*PartialDecryptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{4}
}

func (x *PartialDecryptionRequest) GetEncryptedResult() []byte {
	if x != nil {
		return x.EncryptedResult
	}
	return nil
}

func (x *PartialDecryptionRequest) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *PartialDecryptionRequest) GetRequestStartTime() int64 {
	if x != nil {
		return x.RequestStartTime
	}
	return 0
}

type PartialDecryptionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PartialDecryption []byte                 `protobuf:"bytes,1,opt,name=partial_decryption,json=partialDecryption,proto3" json:"partial_decryption,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PartialDecryptionResponse) Reset() {
	*x = PartialDecryptionResponse{}
	mi := &file_proto_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartialDecryptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialDecryptionResponse) ProtoMessage() {}

func (x *PartialDecryptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialDecryptionResponse.ProtoReflect.Descriptor instead.
func (*PartialDecryptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{5}
}

func (x *PartialDecryptionResponse) GetPartialDecryption() []byte {
	if x != nil {
		return x.PartialDecryption
	}
	return nil
}

var File_proto_service_proto protoreflect.FileDescriptor

const file_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x13proto/service.proto\x12\x10cifar10_ensemble\"\xd2\x03\n" +
	"\x12EnrollModelRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12#\n" +
	"\rconv1_weights\x18\x02 \x03(\fR\fconv1Weights\x12\x1d\n" +
	"\n" +
	"conv1_bias\x18\x03 \x01(\fR\tconv1Bias\x12#\n" +
	"\rconv2_weights\x18\x04 \x03(\fR\fconv2Weights\x12\x1d\n" +
	"\n" +
	"conv2_bias\x18\x05 \x01(\fR\tconv2Bias\x12\x1f\n" +
	"\vfc1_weights\x18\x06 \x03(\fR\n" +
	"fc1Weights\x12\x19\n" +
	"\bfc1_bias\x18\a \x01(\fR\afc1Bias\x12\x1f\n" +
	"\vfc2_weights\x18\b \x01(\fR\n" +
	"fc2Weights\x12\x19\n" +
	"\bfc2_bias\x18\t \x01(\fR\afc2Bias\x12\x1d\n" +
	"\n" +
	"public_key\x18\n" +
	" \x01(\fR\tpublicKey\x12/\n" +
	"\x13relinearization_key\x18\v \x01(\fR\x12relinearizationKey\x12#\n" +
	"\rrotation_keys\x18\f \x03(\fR\frotationKeys\x12,\n" +
	"\x12request_start_time\x18\r \x01(\x03R\x10requestStartTime\"I\n" +
	"\x13EnrollModelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xfb\x01\n" +
	"\x10InferenceRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12'\n" +
	"\x0fencrypted_input\x18\x02 \x03(\fR\x0eencryptedInput\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\x12/\n" +
	"\x13relinearization_key\x18\x04 \x01(\fR\x12relinearizationKey\x12#\n" +
	"\rrotation_keys\x18\x05 \x03(\fR\frotationKeys\x12,\n" +
	"\x12request_start_time\x18\x06 \x01(\x03R\x10requestStartTime\"\x83\x01\n" +
	"\x11InferenceResponse\x12)\n" +
	"\x10encrypted_result\x18\x01 \x01(\fR\x0fencryptedResult\x12C\n" +
	"\x1edecryption_protocol_start_time\x18\x02 \x01(\x03R\x1bdecryptionProtocolStartTime\"\x8e\x01\n" +
	"\x18PartialDecryptionRequest\x12)\n" +
	"\x10encrypted_result\x18\x01 \x01(\fR\x0fencryptedResult\x12\x19\n" +
	"\bparty_id\x18\x02 \x01(\tR\apartyId\x12,\n" +
	"\x12request_start_time\x18\x03 \x01(\x03R\x10requestStartTime\"J\n" +
	"\x19PartialDecryptionResponse\x12-\n" +
	"\x12partial_decryption\x18\x01 \x01(\fR\x11partialDecryption2\xc9\x01\n" +
	"\n" +
	"CSPService\x12\\\n" +
	"\vEnrollModel\x12$.cifar10_ensemble.EnrollModelRequest\x1a%.cifar10_ensemble.EnrollModelResponse\"\x00\x12]\n" +
	"\x10RequestInference\x12\".cifar10_ensemble.InferenceRequest\x1a#.cifar10_ensemble.InferenceResponse\"\x002\x89\x01\n" +
	"\x10DataOwnerService\x12u\n" +
	"\x18PerformPartialDecryption\x12*.cifar10_ensemble.PartialDecryptionRequest\x1a+.cifar10_ensemble.PartialDecryptionResponse\"\x00B\x17Z\x15secure-ensemble/protob\x06proto3"

var (
	file_proto_service_proto_rawDescOnce sync.Once
	file_proto_service_proto_rawDescData []byte
)

func file_proto_service_proto_rawDescGZIP() []byte {
	file_proto_service_proto_rawDescOnce.Do(func() {
		file_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)))
	})
	return file_proto_service_proto_rawDescData
}

var file_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_service_proto_goTypes = []any{
	(*EnrollModelRequest)(nil),        // 0: cifar10_ensemble.EnrollModelRequest
	(*EnrollModelResponse)(nil),       // 1: cifar10_ensemble.EnrollModelResponse
	(*InferenceRequest)(nil),          // 2: cifar10_ensemble.InferenceRequest
	(*InferenceResponse)(nil),         // 3: cifar10_ensemble.InferenceResponse
	(*PartialDecryptionRequest)(nil),  // 4: cifar10_ensemble.PartialDecryptionRequest
	(*PartialDecryptionResponse)(nil), // 5: cifar10_ensemble.PartialDecryptionResponse
}
var file_proto_service_proto_depIdxs = []int32{
	0, // 0: cifar10_ensemble.CSPService.EnrollModel:input_type -> cifar10_ensemble.EnrollModelRequest
	2, // 1: cifar10_ensemble.CSPService.RequestInference:input_type -> cifar10_ensemble.InferenceRequest
	4, // 2: cifar10_ensemble.DataOwnerService.PerformPartialDecryption:input_type -> cifar10_ensemble.PartialDecryptionRequest
	1, // 3: cifar10_ensemble.CSPService.EnrollModel:output_type -> cifar10_ensemble.EnrollModelResponse
	3, // 4: cifar10_ensemble.CSPService.RequestInference:output_type -> cifar10_ensemble.InferenceResponse
	5, // 5: cifar10_ensemble.DataOwnerService.PerformPartialDecryption:output_type -> cifar10_ensemble.PartialDecryptionResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_service_proto_init() }
func file_proto_service_proto_init() {
	if File_proto_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_service_proto_goTypes,
		DependencyIndexes: file_proto_service_proto_depIdxs,
		MessageInfos:      file_proto_service_proto_msgTypes,
	}.Build()
	File_proto_service_proto = out.File
	file_proto_service_proto_goTypes = nil
	file_proto_service_proto_depIdxs = nil
}
